Update Quarkus Sample Description
devfile/registry pull request #179
Opened 2023-04-12 20:19 UTC by johnmcollier

The sample is using OpenJDK 17 now

2023-04-12 20:38 UTC, elsony requested changes
We also need to update the Spring Boot as well.

2023-04-12 20:43 UTC, johnmcollier commented
Updated

2023-04-12 20:44 UTC, elsony approved these changes
/lgtm

2023-05-04 15:07 UTC, elsony approved these changes
/lgtm

2023-05-04 15:07 UTC, merged