Wildfly 2.0.1
devfile/registry pull request #311
Opened 2024-03-04 16:28 UTC by ehsavoie

### What does this PR do?:
Upgrade WildFly stack

- [X] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [X] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [X] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

2024-03-05 17:05 UTC, ehsavoie commented
I don't understand the odo failure as i couldn't reproduce locally

2024-03-05 17:42 UTC, ehsavoie commented
/retest

2024-03-08 14:07 UTC, thepetk requested changes
@ehsavoie added a suggestion which will fix the error:

```
Failed to delete inner loop resources: failed to gather resources for
deletion: yaml: line 39: could not find expected ':'
```

2024-03-08 14:07 UTC, thepetk commented on stacks/java-wildfly/2.0.1/deploy.yaml
> +----
```suggestion

```

2024-03-08 14:28 UTC, thepetk approved these changes
/lgtm

2024-03-13 19:42 UTC, merged