Update stacks/java-websphereliberty/devfile.yaml
devfile/registry pull request #343
Opened 2024-03-25 13:28 UTC by akurinnoy

### What does this PR do?:

- update schema to `2.2.0`;
- use `https` protocol for the `java-websphereliberty` devfile.

### Which issue(s) this PR fixes:
_Link to github issue(s)_

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

https://workspaces.openshift.com/#https://raw.githubusercontent.com/akurinnoy/registry/patch-1/stacks/java-websphereliberty/devfile.yaml

2024-03-25 13:39 UTC, thepetk requested changes
I've added a minor suggestion regarding the name of the endpoint. @ajm01 as you re listed as an owner of this stack, could you please review the PR?

2024-03-25 13:39 UTC, thepetk commented on stacks/java-websphereliberty/devfile.yaml
>            name: http-websphere
```suggestion
          name: https-websphere
```

2024-03-25 13:45 UTC, akurinnoy commented on stacks/java-websphereliberty/devfile.yaml
>            name: http-websphere
@thepetk Thanks for the feedback.

2024-03-25 13:47 UTC, thepetk approved these changes
/lgtm Tested locally with odo 3. I wasn't able to run the `run` command but the failure is not related to this update. As mentioned to my previous comment the PR needs to be approved from the stack owner first in order to be merged.

2024-03-25 13:48 UTC, thepetk commented
/ok-to-test

2024-03-26 08:35 UTC, akurinnoy commented
/retest

2024-04-01 11:06 UTC, thepetk commented
> /lgtm Tested locally with odo 3. I wasn't able to run the `run` command but the failure is not related to this update. As mentioned to my previous comment the PR needs to be approved from the stack owner first in order to be merged.

@akurinnoy I've revisited my initial review. A minor suggestion is to bump up the version of the devfile too

https://github.com/devfile/registry/blob/0ccd117da09d01078dbb82c1f57393c261f69de1/stacks/java-websphereliberty/devfile.yaml#L34

I'd suggest bumping up to `0.10.0`

2024-04-02 11:14 UTC, thepetk reviewed
@ajm01 as you are listed in the OWNERs file could you please review the PR?

2024-04-03 13:11 UTC, ibuziuk approved these changes

2024-04-03 14:11 UTC, thepetk commented
> @thepetk thanks, fixed.

@akurinnoy I think there's a small error with the DCO

2024-04-05 09:52 UTC, svor approved these changes

2024-04-23 10:22 UTC, merged