Update php-laravel devfile
devfile/registry pull request #349
Opened 2024-03-28 23:22 UTC by dkwon17

### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_
1. Created new version folder 2.0.1
2. Updated schema version to 2.2.2
3. Updated endpoint protocol to https
4. Set the default version to 2.0.1 in stack.yaml

### Which issue(s) this PR fixes:
_Link to github issue(s)_

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

2024-04-01 10:49 UTC, thepetk requested changes
Suggested a minor change

2024-04-01 10:49 UTC, thepetk commented on stacks/php-laravel/2.0.1/devfile.yaml
> +        - name: http-laravel
```suggestion
        - name: https-laravel
```

2024-04-02 22:27 UTC, dkwon17 commented
Thank you, I fixed the changes, but I had to force push to my branch to remove the unsigned commit

2024-04-03 09:04 UTC, thepetk commented
> Thank you, I fixed the changes, but I had to force push to my branch to remove the unsigned commit

Thanks! The only thing remains from our side is to address the failing check issue https://github.com/devfile/api/issues/1494

/hold

2024-04-03 09:05 UTC, thepetk approved these changes
/lgtm

2024-04-03 14:06 UTC, thepetk commented
/retest

2024-04-03 14:15 UTC, thepetk commented
@dkwon17 could you please rebase with the latest main. I think the issue with the odov3 check will be fixed

2024-04-04 10:14 UTC, thepetk commented
Tested locally and it looks good.

2024-04-04 10:14 UTC, merged