Adding support for RedHat Jboss EAP 8.0
devfile/registry pull request #430
Opened 2024-06-21 16:16 UTC by ehsavoie

### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_

### Which issue(s) this PR fixes:
_Link to github issue(s)_

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

2024-06-21 16:26 UTC, michael-valdron requested changes
The stack entry should be under [`stacks`](https://github.com/devfile/registry/tree/main/stacks).

2024-06-21 16:26 UTC, michael-valdron commented on java-jboss-eap/OWNERS
Using `CODEOWNERS` file instead of `OWNERS` files now, see: https://github.com/devfile/registry/blob/75ac6fe3cc35ed6a1edd265a45e682f9e98b89e2/.github/CODEOWNERS#L6-L53

2024-06-21 16:29 UTC, ehsavoie commented on java-jboss-eap/OWNERS
Sorry

2024-06-21 16:29 UTC, michael-valdron commented on java-jboss-eap/OWNERS
Should go `/stacks/<stack_name>` followed by owner(s) then followed by `@devfile/che-team`.

2024-06-21 16:33 UTC, michael-valdron commented on stacks/java-jboss-eap/1.0.0/devfile.yaml
> +        uri: Containerfile
Missing resource file `Containerfile`.

2024-06-21 16:33 UTC, michael-valdron commented on stacks/java-jboss-eap/1.0.0/devfile.yaml
> +      uri: deploy.yaml
Missing resource file `deploy.yaml`.

2024-06-24 08:46 UTC, ehsavoie commented on java-jboss-eap/OWNERS
ok

2024-06-24 08:47 UTC, ehsavoie commented on stacks/java-jboss-eap/1.0.0/devfile.yaml
> +        uri: Containerfile
Those are leftovers, removed

2024-06-24 08:47 UTC, ehsavoie commented on stacks/java-jboss-eap/1.0.0/devfile.yaml
> +      uri: deploy.yaml
Those are leftovers, removed

2024-06-25 11:19 UTC, ehsavoie commented
@thepetk the image is an official one: https://catalog.redhat.com/software/containers/devspaces/udi-rhel8/622bce914a14c05796114be4?architecture=amd64&image=665692c9c86066cb957cbbde&container-tabs=gti&gti-tabs=registry-tokens

2024-06-25 15:46 UTC, closed without merging