Deactivate Quarkus telemetry causing stacktrace
devfile/registry pull request #443
Opened 2024-07-05 08:24 UTC by apupier

Users won't have the possibility to answer to the question and we need to keep it opt-in

fixes devfile/api#1611

### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_

### Which issue(s) this PR fixes:
_Link to github issue(s)_

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

2024-07-05 11:03 UTC, thepetk reviewed
Needs review from @maxandersen as the stack owner

2024-07-22 17:11 UTC, maxandersen commented
On pto but was the original issue reported somewhere as user should not get an error for this.

2024-07-24 19:49 UTC, Jdubrick reviewed
/ok-to-test

2024-08-01 10:33 UTC, maxandersen requested changes
not a fan as fix happening and will make it not be so noisy.

afaik this is only issue in che for some reason it doesn't handle terminal/tty?

2024-08-05 11:23 UTC, apupier commented
> not a fan as fix happening and will make it not be so noisy.

If I understand well the [fix](https://github.com/quarkusio/quarkus/pull/42071), it will remain this message in log:

```
tools: ----------------------------
tools: --- Help improve Quarkus ---
tools: ----------------------------
tools: * Learn more: https://quarkus.io/usage/
tools: * Do you agree to contribute anonymous build time data to the Quarkus community? (y/n and enter) 
tools: [info] [Quarkus build analytics] Didn't receive a valid user's answer: `y` or `n`. The question will be asked again next time.
```

I feel like this will be nicer anyway to not have a this kind of log. It will also avoid to raise an exception which should gain few milliseconds.

> afaik this is only issue in che for some reason it doesn't handle terminal/tty?

It is not only in Che context. Currently, it is when using odo and deploy on an OpenShift instance. Hich is something that can be used from local command-line, VS Code OpenShift toolkit, IntelliJ OpenShift extension; both locally or inside Che.

2025-09-09 15:17 UTC, michael-valdron commented
Hi @apupier and @maxandersen,

Is this PR still in review? @maxandersen Is there a follow to @apupier comment on these changes?

If there is no activity in the next month we'll be closing this PR as stale.

2025-10-08 07:50 UTC, apupier commented
closing as stale

2025-10-08 07:50 UTC, closed without merging