ginkgo skip jhipster-online
devfile/registry pull request #508
Opened 2024-12-09 20:10 UTC by maximilianoPizarro

# Description of Changes

Only add --skip="stack: jhipster-online version: 2.23.0 starter: jhipster-online" from file tests/check_odov3.sh. Because fail in the step "with odo v3".

Example error in the last job:

https://github.com/devfile/registry/actions/runs/12200513685/job/34042081550

Summarizing 1 Failure:
[FAIL] test starter projects from devfile stacks [It] stack: jhipster-online version: 2.33.0 no_starter
/home/runner/work/registry/registry/tests/odov3/odo_test.go:192

2024-12-09 21:02 UTC, thepetk reviewed
Looks good to me, I'm just checking why the odo 3 check fails. I'm sure is not related with the current PR. I'll give it a bit of time till I re-run it if it fails again. I see the nightly run didn't exit for the same reason.

2024-12-09 21:14 UTC, Jdubrick reviewed
/ok-to-test

I think the failure in CI is related to the mirror url, it might just be down currently

2024-12-09 21:15 UTC, thepetk commented
> /ok-to-test
> 
> I think the failure in CI is related to the mirror url, it might just be down currently

yeah I suspect so too. I guess let's give it some time

2024-12-09 21:31 UTC, michael-valdron commented
/retest

2024-12-10 05:19 UTC, michael-valdron commented
Bug reported failing check: devfile/api#1656

2024-12-13 15:11 UTC, michael-valdron commented
/retest

2024-12-13 15:13 UTC, michael-valdron commented
@maximilianoPizarro Suggest a rebase, if the updated Red Hat Konflux check fails we can bypass it for this PR.

2024-12-18 16:10 UTC, michael-valdron requested changes

2024-12-18 16:10 UTC, michael-valdron commented on tests/check_odov3.sh
> +  --skip="stack: jhipster-online version: 2.23.0 starter: jhipster-online" \
Your stack version might be a typo:
```suggestion
  --skip="stack: jhipster-online version: 2.33.0 starter: jhipster-online" \
```

2024-12-18 17:37 UTC, maximilianoPizarro commented on tests/check_odov3.sh
> +  --skip="stack: jhipster-online version: 2.23.0 starter: jhipster-online" \
Thanks Michael, I send the change.

2024-12-18 17:56 UTC, michael-valdron approved these changes
/lgtm

2024-12-18 19:31 UTC, maximilianoPizarro commented
Hi Michael again.
I see there are other projects that are affected. 

```bash
Container test exited with code 1, reason Error
---
led
+ for test in '"${FAILED_TESTS[@]}"'
+ echo 'name: nodejs-nuxtjs version: 1.0.3 error: create failed'
name: nodejs-nuxtjs version: 1.0.3 error: create failed
+ for test in '"${FAILED_TESTS[@]}"'
+ echo 'name: nodejs-nuxtjs version: 1.1.0 error: create failed'
name: nodejs-nuxtjs version: 1.1.0 error: create failed
+ for test in '"${FAILED_TESTS[@]}"'
+ echo 'name: nodejs-react version: 2.0.2 error: unable to get working url'
name: nodejs-react version: 2.0.2 error: unable to get working url
+ for test in '"${FAILED_TESTS[@]}"'
+ echo 'name: nodejs-react version: 2.1.0 error: unable to get working url'
name: nodejs-react version: 2.1.0 error: unable to get working url
+ for test in '"${FAILED_TESTS[@]}"'
+ echo 'name: nodejs-svelte version: 1.0.3 error: unable to get working url'
name: nodejs-svelte version: 1.0.3 error: unable to get working url
+ for test in '"${FAILED_TESTS[@]}"'
+ echo 'name: nodejs-svelte version: 1.1.0 error: unable to get working url'
name: nodejs-svelte version: 1.1.0 error: unable to get working url
+ for test in '"${FAILED_TESTS[@]}"'
+ echo 'name: nodejs-vue version: 1.0.2 error: unable to get working url'
name: nodejs-vue version: 1.0.2 error: unable to get working url
+ for test in '"${FAILED_TESTS[@]}"'
+ echo 'name: nodejs-vue version: 1.1.0 error: unable to get working url'
name: nodejs-vue version: 1.1.0 error: unable to get working url
+ for test in '"${FAILED_TESTS[@]}"'
+ echo 'name: php-laravel version: 1.0.1 error: create failed'
name: php-laravel version: 1.0.1 error: create failed
+ for test in '"${FAILED_TESTS[@]}"'
+ echo 'name: python version: 2.1.0 error: create failed'
name: python version: 2.1.0 error: create failed
+ exit 1
```

Would you like me to add them to the ginkgo skip list in this PR?

2024-12-18 21:53 UTC, michael-valdron commented
> Hi @michael-valdron again. I see there are other projects that are affected.
> 
> ```shell
> Container test exited with code 1, reason Error
> ---
> led
> + for test in '"${FAILED_TESTS[@]}"'
> + echo 'name: nodejs-nuxtjs version: 1.0.3 error: create failed'
> name: nodejs-nuxtjs version: 1.0.3 error: create failed
> + for test in '"${FAILED_TESTS[@]}"'
> + echo 'name: nodejs-nuxtjs version: 1.1.0 error: create failed'
> name: nodejs-nuxtjs version: 1.1.0 error: create failed
> + for test in '"${FAILED_TESTS[@]}"'
> + echo 'name: nodejs-react version: 2.0.2 error: unable to get working url'
> name: nodejs-react version: 2.0.2 error: unable to get working url
> + for test in '"${FAILED_TESTS[@]}"'
> + echo 'name: nodejs-react version: 2.1.0 error: unable to get working url'
> name: nodejs-react version: 2.1.0 error: unable to get working url
> + for test in '"${FAILED_TESTS[@]}"'
> + echo 'name: nodejs-svelte version: 1.0.3 error: unable to get working url'
> name: nodejs-svelte version: 1.0.3 error: unable to get working url
> + for test in '"${FAILED_TESTS[@]}"'
> + echo 'name: nodejs-svelte version: 1.1.0 error: unable to get working url'
> name: nodejs-svelte version: 1.1.0 error: unable to get working url
> + for test in '"${FAILED_TESTS[@]}"'
> + echo 'name: nodejs-vue version: 1.0.2 error: unable to get working url'
> name: nodejs-vue version: 1.0.2 error: unable to get working url
> + for test in '"${FAILED_TESTS[@]}"'
> + echo 'name: nodejs-vue version: 1.1.0 error: unable to get working url'
> name: nodejs-vue version: 1.1.0 error: unable to get working url
> + for test in '"${FAILED_TESTS[@]}"'
> + echo 'name: php-laravel version: 1.0.1 error: create failed'
> name: php-laravel version: 1.0.1 error: create failed
> + for test in '"${FAILED_TESTS[@]}"'
> + echo 'name: python version: 2.1.0 error: create failed'
> name: python version: 2.1.0 error: create failed
> + exit 1
> ```
> 
> Would you like me to add them to the ginkgo skip list in this PR?

@maximilianoPizarro Thanks for offering but not necessary, these failures are caused by an issue with our testing environment: https://github.com/devfile/api/issues/1663

Also another issue regarding other stacks using the 2.2.2 spec by default but not being exempt from the odo v2 testing that our integration testing uses.

For your PR, I can run our integration testing locally for you tomorrow and bypass the failing check if everything passes as nothing I am seeing is being cause by your changes.

2024-12-19 10:18 UTC, thepetk commented
/retest

2024-12-19 19:36 UTC, michael-valdron approved these changes
/lgtm

@maximilianoPizarro I was able to run your change successfully on my side: [test_log.txt](https://github.com/user-attachments/files/18202371/test_log.txt)

All but the failures due to devfile/api#1664:
```
The following tests failed:
name: java-springboot version: 1.2.0 error: create failed
name: java-springboot version: 1.3.0 error: create failed
name: java-wildfly version: 1.1.0 error: create failed
name: nodejs version: 2.1.1 error: create failed
name: nodejs version: 2.2.0 error: create failed
name: nodejs-angular version: 2.0.2 error: create failed
name: nodejs-angular version: 2.1.0 error: create failed
name: nodejs-nextjs version: 1.0.3 error: create failed
name: nodejs-nextjs version: 1.1.0 error: create failed
name: nodejs-nuxtjs version: 1.0.3 error: create failed
name: nodejs-nuxtjs version: 1.1.0 error: create failed
name: php-laravel version: 1.0.1 error: create failed
name: python version: 2.1.0 error: create failed
name: java-maven version: 1.2.0 error: create failed
name: java-maven version: 1.3.0 error: create failed
name: java-vertx version: 1.2.0 error: create failed
name: java-vertx version: 1.3.0 error: create failed
```

Since these are unrelated to your change and this stack is not on this list I will bypass the protection to merge your PR.

@thepetk Does everything look good from your side?

2024-12-20 17:27 UTC, thepetk approved these changes

2024-12-20 17:29 UTC, thepetk commented
> /lgtm
> 
> @maximilianoPizarro I was able to run your change successfully on my side: [test_log.txt](https://github.com/user-attachments/files/18202371/test_log.txt)
> 
> All but the failures due to devfile/api#1664:
> ```
> The following tests failed:
> name: java-springboot version: 1.2.0 error: create failed
> name: java-springboot version: 1.3.0 error: create failed
> name: java-wildfly version: 1.1.0 error: create failed
> name: nodejs version: 2.1.1 error: create failed
> name: nodejs version: 2.2.0 error: create failed
> name: nodejs-angular version: 2.0.2 error: create failed
> name: nodejs-angular version: 2.1.0 error: create failed
> name: nodejs-nextjs version: 1.0.3 error: create failed
> name: nodejs-nextjs version: 1.1.0 error: create failed
> name: nodejs-nuxtjs version: 1.0.3 error: create failed
> name: nodejs-nuxtjs version: 1.1.0 error: create failed
> name: php-laravel version: 1.0.1 error: create failed
> name: python version: 2.1.0 error: create failed
> name: java-maven version: 1.2.0 error: create failed
> name: java-maven version: 1.3.0 error: create failed
> name: java-vertx version: 1.2.0 error: create failed
> name: java-vertx version: 1.3.0 error: create failed
> ```
> 
> Since these are unrelated to your change and this stack is not on this list I will bypass the protection to merge your PR.
> 
> @thepetk Does everything look good from your side?

Yeah tbh I don't see any issues merging this PR

2024-12-20 17:30 UTC, merged